# Generated by Django 4.2 on 2023-11-29 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Time_Stamp',
            new_name='created_at',
        ),
    ]
